ImagineHacks/urls.py
from django.contrib import admin
from django.urls import path
from Backend import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.name, name='name'),    
    path('xray', views.xRay, name='xray'),    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Backend/models.py
from django.db import models

# Create your models here.

class xRayy(models.Model):
    xray_img = models.ImageField(upload_to='xray/')
    output_one = models.ImageField(upload_to='output/',default='',null=True,blank=True)
    

Backend/forms.py
from django import forms
from .models import *

class xRayForm(forms.ModelForm):
    class Meta:
        model = xRayy
        fields = ["xray_img",]

Backend/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import xRayy
from .forms import xRayForm

import numpy as np
import pandas as pa
import cv2
import gc
import os
import seaborn as sn 
# import matplotlib.pyplot as plt

from InceptionV3.Neural_Visuals import Neural_Visuals

from tensorflow.keras.models import Model
from tensorflow.keras.layers import AveragePooling2D,MaxPooling2D,Dropout,Flatten,Dense,Input
from tensorflow.keras.optimizers import Adam,RMSprop
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.applications.inception_v3 import InceptionV3
from tensorflow.keras.applications.vgg19 import VGG19
from tensorflow.keras.applications.resnet50 import ResNet50
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix

from imutils import paths
import tensorflow as tf

model = tf.keras.models.load_model('Models/covid_model.h5')

# Create your views here.

def name(request):
    xrayy=xRayy.objects.all()
    return render(request, "./index.html", {'xRayForm': xRayForm(), 'xrayy':xrayy})

def xRay(request):
    global model
    img = request.FILES['xray_img']    
    path = "D:/GitHub/ImagineHacks/media/xray/"+str(img)
    inp = xRayy.objects.create(xray_img=img)
    pkk=inp.pk
    obj = Neural_Visuals()
    output = obj.visualize(path,model)
    out_path = 'D:/GitHub/ImagineHacks/media/output/'
    cv2.imwrite(os.path.join(out_path , str(img)), output[0])
    label = output[1]
    data_out_path = str(out_path + str('/')+str(img))
    xRayy.objects.filter(pk=pkk).update(output_one=data_out_path)
    out_label = ''
    if label == 0:
        out_label = 'The person has covid'
    elif label == 1:
        out_label = 'The person is not infected'
    else:
        out_label = 'The person has phenemonia'
    img_inp_path = str("/media/xray/" + str(img))
    img_out_path = str("/media/output/" + str(img))
    context = {
        'out_label':out_label,
        'pkk':pkk,
        'inp':img_inp_path,
        'out':img_out_path,
    }
    return render(request, "./xray.html", context=context)

Backend/templates/base.html
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js" integrity="sha512-dqw6X88iGgZlTsONxZK9ePmJEFrmHwpuMrsUChjAw1mRUhUITE5QU9pkcSox+ynfLhL15Sv2al5A0LVyDCmtUw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" integrity="sha512-8bHTC73gkZ7rZ7vpqUQThUDhqcNFyYi2xgDgPDHc+GXVGHXq+xPjynxIopALmOPqzo9JZj0k6OqqewdGO3EsrQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
    <title>Document</title>
</head>
<style>
body {
    background-color: #F9F9FB;
}
.files input {
    outline: 2px dashed #92b0b3;
    outline-offset: -10px;
    -webkit-transition: outline-offset .15s ease-in-out, background-color .15s linear;
    transition: outline-offset .15s ease-in-out, background-color .15s linear;
    padding: 120px 0px 85px 35%;
    text-align: center !important;
    margin: 0;
    width: 100% !important;
}
.files input:focus{     outline: 2px dashed #92b0b3;  outline-offset: -10px;
    -webkit-transition: outline-offset .15s ease-in-out, background-color .15s linear;
    transition: outline-offset .15s ease-in-out, background-color .15s linear; border:1px solid #92b0b3;
 }
.files{ position:relative}
.files:after {  pointer-events: none;
    position: absolute;
    top: 60px;
    left: 0;
    width: 50px;
    right: 0;
    height: 56px;
    content: "";
    background-image: url(https://image.flaticon.com/icons/png/128/109/109612.png);
    display: block;
    margin: 0 auto;
    background-size: 100%;
    background-repeat: no-repeat;
}
.color input{ background-color:#f1f1f1;}
.files:before {
    position: absolute;
    bottom: 10px;
    left: 0;  pointer-events: none;
    width: 100%;
    right: 0;
    height: 57px;
    content: " or drag it here. ";
    display: block;
    margin: 0 auto;
    color: #2ea591;
    font-weight: 600;
    text-transform: capitalize;
    text-align: center;
}
</style>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <a class="navbar-brand" href="{% url 'name' %}">Covid Detector</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="#">Features</a>
                    </li>
                </ul>
                <div class="my-2 my-lg-0">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a href="#" class="nav-link active">About</a>
                        </li>
                    </ul>
                </form>
            </div>
        </div>
    </nav>
{% block content %}
{% endblock %}
<script>
    var loadFile = function(event) {
      var output = document.getElementById('output');
      output.src = URL.createObjectURL(event.target.files[0]);
      output.onload = function() {
        URL.revokeObjectURL(output.src) // free memory
      }
    };
</script>
</body>

Backend/templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="container pt-5">
    <div class="row">

        <div class="col-md-6" style="display: block; margin: 0 auto;">
            <form action="{% url 'xray' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group files" style="box-shadow: 0 0 10px rgb(206, 212, 218); border-radius: 10px;">
                    <label hidden style="display: block; margin: 0 auto; text-align: center;" class="mb-1" for="id_xray_img">Upload Your File </label>
                    <input type="file" name="xray_img" accept="image/*" class="form-control" height=500 required="" id="id_xray_img" onchange="loadFile(event)">
                </div>
                <span>
                    <button type="submit" class="btn btn-primary text-center" style="display: block; margin: 0 auto;">Submit</button>
                </span>
                <div class="mt-3" style="border: 1px solid rgb(206, 212, 218); padding: 10px; background-color: #fff; box-shadow: 0 0 10px rgb(206, 212, 218); border-radius: 30px;">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus porro qui harum necessitatibus laudantium voluptatum earum dolorem atque, reprehenderit saepe, ullam neque magnam possimus numquam rerum totam dolores error id?
                    <br>
                    Eum repellat ea nulla asperiores quam quibusdam eaque aut quae at qui, ratione ad autem laboriosam ab? Dolor earum eligendi odit error deleniti praesentium magni est blanditiis delectus quod? Aperiam!
                    <br>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis, ducimus repellat dignissimos tempore inventore, quaerat veritatis sint, placeat tempora corporis dolorem sequi eveniet libero quisquam consectetur expedita eos vero at.
                    <br>
                    Repellendus explicabo molestias in nam voluptatum delectus a nihil, quasi iure, tempore voluptatem et nulla enim. Dicta repellat temporibus dolorem ex, aperiam numquam tempore dolor nulla. Dolor repellat reiciendis adipisci!
                </div>
            </form>
        </div>

        <div class="col-md-6" style="height: 570px; overflow: hidden; display: block; margin: 0 auto; text-align: center; border: 1px solid rgb(206, 212, 218); padding: 10px; background-color: #fff; box-shadow: 0 0 10px rgb(206, 212, 218); border-radius: 30px;">
            <h4 style="text-align: center; text-transform: uppercase; letter-spacing: 3px; color: #007BFF;">Input</h4>
            <img id="output" style="height: 60%; border-radius: 30px;" />
        </div>
    </div>
</div>
{% endblock %}

Backend/templates/xray.html
{% extends "base.html" %}
{% block content %}
    
    <br>
    {% if pkk %}
        <img >
        <h4 style="text-align: center; text-transform: uppercase; letter-spacing: 3px; color: #007BFF;">{{ out_label }}</h4>
        <div class="container mt-1" style="width: 100%;">
            <div class="row" style="text-align: center;  height: 50%; border: 1px solid rgb(206, 212, 218); padding: 10px 0px; background-color: #fff; box-shadow: 0 0 10px rgb(206, 212, 218); border-radius: 30px;">
                <div class="col-md-6" style="height: 400px;">
                    <img src="{{ inp }}" alt="" style="border-radius: 30px; height: 100%;" />
                    <h5 style="text-align: center; text-transform: uppercase; letter-spacing: 3px; color: #007BFF;">input</h5>
                </div>
                <div class="col-md-6" style="height: 400px;">
                    <img src="{{ out }}" alt="" style="border-radius: 30px; height: 100%;" />
                    <h5 style="text-align: center; text-transform: uppercase; letter-spacing: 3px; color: #007BFF;">output</h5>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}